import { SaleType } from "./types";
import { nanoid } from "nanoid";

export const salesData: SaleType[] = [
  {
    id: nanoid(),
    customerName: "John Adeniyi",
    dealValue: "₦12,500",
    status: "In Progress",
    contactDate: "2024-11-15",
    salesperson: "Alice Smith",
    priority: "High",
  },
  {
    id: nanoid(),
    customerName: "Jane Smith",
    dealValue: "₦8,000",
    status: "Closed",
    contactDate: "2024-11-13",
    salesperson: "Johnson Williams",
    priority: "Medium",
  },
  {
    id: nanoid(),
    customerName: "Mark Balogun",
    dealValue: "₦15,300",
    status: "Negotiation",
    contactDate: "2024-11-14",
    salesperson: "Sarah Ifedayo",
    priority: "High",
  },
  {
    id: nanoid(),
    customerName: "Emily Oluyemo",
    dealValue: "₦3,750",
    status: "Pending",
    contactDate: "2024-11-12",
    salesperson: "Busari Idowu",
    priority: "Low",
  },
  {
    id: nanoid(),
    customerName: "Chris Lambe",
    dealValue: "₦6,600",
    status: "Closed",
    contactDate: "2024-11-11",
    salesperson: "Kehinde Musa",
    priority: "Medium",
  },
  {
    id: nanoid(),
    customerName: "Sophia Alakija",
    dealValue: "₦10,400",
    status: "In Progress",
    contactDate: "2024-11-10",
    salesperson: "Bashir Lawal",
    priority: "High",
  },
  {
    id: nanoid(),
    customerName: "Grace Olukeye",
    dealValue: "₦7,200",
    status: "Pending",
    contactDate: "2024-11-12",
    salesperson: "Lola Balogun",
    priority: "Low",
  },
  {
    id: nanoid(),
    customerName: "Olivia Adeniyi",
    dealValue: "₦9,600",
    status: "Negotiation",
    contactDate: "2024-11-13",
    salesperson: "David Olayiwola",
    priority: "Medium",
  },
  {
    id: nanoid(),
    customerName: "Mosun Olaniyi",
    dealValue: "₦5,750",
    status: "Closed",
    contactDate: "2024-11-14",
    salesperson: "Sophia Evans",
    priority: "Low",
  },
  {
    id: nanoid(),
    customerName: "Emma Charles",
    dealValue: "₦14,300",
    status: "In Progress",
    contactDate: "2024-11-07",
    salesperson: "James Alabi",
    priority: "High",
  },
  {
    id: nanoid(),
    customerName: "Lukman Oluyemo",
    dealValue: "₦3,850",
    status: "Pending",
    contactDate: "2024-11-06",
    salesperson: "Emily Charles",
    priority: "Medium",
  },
  {
    id: nanoid(),
    customerName: "Hailey Babatunde",
    dealValue: "₦13,200",
    status: "Negotiation",
    contactDate: "2024-11-08",
    salesperson: "Adams Oshiomole",
    priority: "High",
  },
  {
    id: nanoid(),
    customerName: "Elijah Remilekun",
    dealValue: "₦4,900",
    status: "Closed",
    contactDate: "2024-11-09",
    salesperson: "Taiwo Grace",
    priority: "Low",
  },
  {
    id: nanoid(),
    customerName: "Isabella Idibia",
    dealValue: "₦8,400",
    status: "In Progress",
    contactDate: "2024-11-01",
    salesperson: "Yusuf Tomori",
    priority: "Medium",
  },
  {
    id: nanoid(),
    customerName: "James Ibori",
    dealValue: "₦10,100",
    status: "Pending",
    contactDate: "2024-11-02",
    salesperson: "Dauda kareem",
    priority: "Low",
  },
];